package org.revature.ERS.org.revature.ERS;

import java.io.IOException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class DBUtilities {

	Connection connection = null;
	Statement statement = null;
	ResultSet resultSet = null;
	PreparedStatement preparedStatement = null;

	public DBUtilities() throws SQLException, IOException {

		try {
			connection = DriverManager.getConnection(
					"jdbc:postgresql://myersdb.cgzlzv0lyi3b.us-east-2.rds.amazonaws.com:5432/myersdb", "myersdb",
					"myersdb123");
		} catch (SQLException ex) {
			System.out.println("The following error has occured: " + ex.getMessage());
		}

	}
	
	public void DisconnectFromDB() {

        try {
            resultSet.close();
            statement.close();
            preparedStatement.close();
            connection.close();
        }                                              
        catch (Exception ex) {
            System.out.println("The following error has occured: " + ex.getMessage());
        }   
    }

}
